server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.util.DriverDataSource
mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.zhaohq.spring.entity
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.zhaohq.spring.entity
  configuration:
    map-underscore-to-camel-case: true # 开启将下划线表格字段，转转为驼峰命名属性
